const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const bytes=Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlS8AAAAASUVORK5CYII=','base64'));
const payload=(extra={})=>({week:4,mimeType:'image/png',dataUrl:'data:image/png;base64,'+Buffer.from(bytes).toString('base64'),caption:'caption',fileName:'a.png',requestId:'test-request-00000001',...extra});
function fixture(){
 const rows=[['Timestamp','Week','Name','Email','Caption','PhotoUrl','DriveFileId','Approved']],files=[],fetches=[];let role='master',appendError=false,sharingError=false,locked=false;
 const sheet={getDataRange:()=>({getValues:()=>rows}),getLastRow:()=>rows.length,appendRow:row=>{if(appendError)throw Error('Sheets unavailable');rows.push(row);},getRange:(r,col)=>({getValues:()=>[rows[r-1]],setValue:v=>{rows[r-1][col-1]=v;}})};
 const folder={getFilesByName:name=>{const result=files.filter(f=>f.name===name);let i=0;return {hasNext:()=>i<result.length,next:()=>result[i++]};},createFile:blob=>{assert.equal(locked,true);const f={name:blob.name,blob,description:'',trashed:false,getId:()=>String(files.indexOf(f)+1),getDescription:()=>f.description,setDescription:v=>{f.description=v;},isTrashed:()=>f.trashed,setTrashed:v=>{f.trashed=v;},setSharing:()=>{if(sharingError)throw Error('sharing disabled');f.shared=true;}};files.push(f);return f;}};
 const c=vm.createContext({console,GAME_SHEETS_51:{CONFIG:'Config',PHOTOS:'Photos'},verifyAdminPasscode:()=>{if(role==='bad')throw Error('Invalid admin passcode');return role;},verifyMasterAdminPasscodeOrThrow_:()=>{if(role!=='master')throw Error('MASTER admin required');},SpreadsheetApp:{getActive:()=>({})},mustGetSheet_:()=>sheet,readConfig_:()=>({PhotoDriveFolderId:'folder'}),sanitizeHtml51_:s=>s,sanitizeFileName_:s=>s,logAdminChange51_(){},LockService:{getScriptLock:()=>({waitLock(){locked=true;},releaseLock(){locked=false;}})},DriveApp:{getFolderById:()=>folder,getRootFolder:()=>folder,Access:{ANYONE_WITH_LINK:1},Permission:{VIEW:1}},Utilities:{getUuid:()=>crypto.randomUUID(),base64Encode:b=>Buffer.from(b).toString('base64'),base64Decode:s=>Array.from(Buffer.from(s,'base64')),newBlob:(b,mimeType,name)=>({bytes:b,mimeType,name}),DigestAlgorithm:{SHA_256:1},computeDigest:(_,b)=>Array.from(crypto.createHash('sha256').update(Buffer.from(b)).digest())},UrlFetchApp:{fetch:(url,options)=>{fetches.push({url,options});return c.response(url);}}});
 vm.runInContext(fs.readFileSync('recap-photos.gs','utf8'),c);
 c.response=()=>response();
 return {c,rows,files,fetches,role:v=>role=v,appendError:v=>appendError=v,sharingError:v=>sharingError=v,locked:()=>locked};
}
function response(status=200,headers={'Content-Type':'image/png'},content=bytes){return {getResponseCode:()=>status,getHeaders:()=>headers,getContent:()=>content};}
test('URL preview returns downloaded bytes and creates no photo record or stored file',()=>{const f=fixture();const result=f.c.previewRecapImageUrl('admin',{week:4,url:'https://example.com/photo.png'});assert.equal(result.week,4);assert.equal(result.dataUrl,payload().dataUrl);assert.equal(f.rows.length,1);assert.equal(f.files.length,0);assert.equal(f.fetches[0].options.followRedirects,false);assert.equal(f.fetches[0].options.validateHttpsCertificates,true);});
test('public redirects are followed and every redirect is revalidated',()=>{const f=fixture();f.c.response=url=>url.endsWith('/start')?response(302,{Location:'/image.png'}):response();assert.equal(f.c.previewRecapImageUrl('admin',{week:2,url:'https://example.com/start'}).week,2);assert.equal(f.fetches[1].url,'https://example.com/image.png');f.c.response=()=>response(302,{Location:'http://127.0.0.1/a'});assert.throws(()=>f.c.previewRecapImageUrl('admin',{week:2,url:'https://example.com/start'}),/could not be imported/);});
test('non-images, login, blocking, server errors, unsupported formats and oversized responses fail without writes',()=>{
 for(const r of [response(200,{'Content-Type':'text/html'}),response(401),response(403),response(404),response(500),response(200,{'Content-Type':'image/svg+xml'}),response(200,{'Content-Type':'image/heic'}),response(200,{'Content-Type':'image/png'},Array.from(Buffer.from('<html>login</html>'))),response(200,{'Content-Type':'image/png','Content-Length':4000000}),response(200,{'Content-Type':'image/png'},new Array(3145729).fill(0))]){const f=fixture();f.c.response=()=>r;assert.throws(()=>f.c.previewRecapImageUrl('admin',{week:4,url:'https://example.com/a'}),/This image could not be imported/);assert.equal(f.files.length,0);assert.equal(f.rows.length,1);}
});
test('unsafe URL schemes, credentials, local addresses and redirect loops fail',()=>{for(const url of ['file:///etc/passwd','data:image/png;base64,AA==','http://localhost/a','http://127.0.0.1/a','http://[::1]/a','https://user:password@example.com/a','https://metadata.google.internal/a','http://example.com:8080/a','https://example.com\\@localhost/a']){const f=fixture();assert.throws(()=>f.c.previewRecapImageUrl('admin',{week:4,url}),/could not be imported/);assert.equal(f.fetches.length,0);}const f=fixture();f.c.response=()=>response(302,{Location:'/loop'});assert.throws(()=>f.c.previewRecapImageUrl('admin',{week:4,url:'https://example.com/a'}),/too many/);assert.equal(f.fetches.length,6);});
test('network failure is sanitized instead of exposing source credentials or internals',()=>{const f=fixture();f.c.response=()=>{throw Error('secret source detail');};assert.throws(()=>f.c.previewRecapImageUrl('admin',{week:4,url:'https://example.com/a'}),e=>/Download failed/.test(e.message)&&!e.message.includes('secret'));});
test('photo upload stores internal URL, same week, bytes and caption without changing schema',()=>{const f=fixture();const result=f.c.saveRecapPhoto51_('admin',payload());assert.equal(f.rows.length,2);assert.equal(f.rows[1].length,8);assert.equal(f.rows[1][1],4);assert.equal(f.rows[1][4],'caption');assert.equal(f.rows[1][5],'https://lh3.googleusercontent.com/d/1');assert.equal(result.photoUrl,f.rows[1][5]);assert.deepEqual(f.files[0].blob.bytes,bytes);assert.equal(f.files[0].shared,true);assert.equal(f.locked(),false);});
test('lost-response retries reuse same stored image and never duplicate rows',()=>{const f=fixture();f.c.saveRecapPhoto51_('admin',payload());const result=f.c.saveRecapPhoto51_('admin',payload());assert.equal(result.alreadySaved,true);assert.equal(f.rows.length,2);assert.equal(f.files.length,1);assert.throws(()=>f.c.saveRecapPhoto51_('admin',payload({week:5})),/different photo or recap/);assert.equal(f.rows.length,2);});
test('retry after failed row append uses existing file and fixed request identity',()=>{const f=fixture();f.appendError(true);assert.throws(()=>f.c.saveRecapPhoto51_('admin',payload()),/Retry/);assert.equal(f.rows.length,1);assert.equal(f.files.length,1);f.appendError(false);f.c.saveRecapPhoto51_('admin',payload());assert.equal(f.files.length,1);assert.equal(f.rows.length,2);});
test('unshareable images create no row and the failed stored copy is trashed',()=>{const f=fixture();f.sharingError(true);assert.throws(()=>f.c.saveRecapPhoto51_('admin',payload()),/could not be stored/);assert.equal(f.rows.length,1);assert.equal(f.files[0].trashed,true);});
test('backend rejects invalid weeks, oversized data, and forged image types before creating files',()=>{for(const data of [payload({week:0}),payload({week:1.5}),payload({week:undefined}),payload({mimeType:'image/svg+xml'}),payload({dataUrl:'data:image/png;base64,'+Buffer.alloc(3145729).toString('base64')}),payload({dataUrl:'data:image/png;base64,PGh0bWw+bG9naW48L2h0bWw+'})]){const f=fixture();assert.throws(()=>f.c.saveRecapPhoto51_('admin',data));assert.equal(f.files.length,0);assert.equal(f.rows.length,1);}});
test('remove and restore affect only matching photo/week, preserving file, caption and reactions identity',()=>{const f=fixture();f.c.saveRecapPhoto51_('admin',payload());const photo=f.c.getAdminRecapPhotos('admin',4).photos[0];assert.equal(f.c.getAdminRecapPhotos('admin',5).photos.length,0);const original=f.rows[1].slice(0,7);assert.throws(()=>f.c.adminSetRecapPhotoRemoved('admin',{...photo,week:5,removed:true}),/does not match/);assert.throws(()=>f.c.adminSetRecapPhotoRemoved('admin',{...photo,photoUrl:'wrong',removed:true}),/does not match/);f.c.adminSetRecapPhotoRemoved('admin',{...photo,removed:true});assert.equal(f.rows[1][7],'FALSE');assert.deepEqual(f.rows[1].slice(0,7),original);assert.equal(f.files[0].trashed,false);f.c.saveRecapPhoto51_('admin',payload());assert.equal(f.rows[1][7],'FALSE');f.c.adminSetRecapPhotoRemoved('admin',{...photo,removed:false});assert.equal(f.rows[1][7],'TRUE');});
test('every photo endpoint enforces existing admin permissions before fetching or writing',()=>{for(const role of ['bad','limited']){const f=fixture();f.role(role);for(const fn of [()=>f.c.previewRecapImageUrl('x',{week:4,url:'https://example.com/a'}),()=>f.c.saveRecapPhoto51_('x',payload()),()=>f.c.getAdminRecapPhotos('x',4),()=>f.c.adminSetRecapPhotoRemoved('x',{week:4,rowNumber:2,removed:true})])assert.throws(fn,/admin/i);assert.equal(f.fetches.length,0);assert.equal(f.files.length,0);}const f=fixture();f.role('recap');assert.equal(f.c.previewRecapImageUrl('x',{week:4,url:'https://example.com/a'}).week,4);});
