const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const source=fs.readFileSync('index.html','utf8');
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlS8AAAAASUVORK5CYII=';
function fixture(){
 const elements={},requests=[],pending=[],modals=[];let refreshes=0;
 const get=id=>elements[id] ||= {value:id==='adminRecapWeek'?'4':'',disabled:false,textContent:'',innerHTML:'',setAttribute(){},classList:{toggle(){}}};
 const c=vm.createContext({console,crypto,setTimeout,clearTimeout,Image:class{set src(v){if(v)queueMicrotask(()=>{this.naturalWidth=this.naturalHeight=1;v.includes('corrupt')?this.onerror():this.onload();});}},document:{getElementById:get},getRichEditorHtml:()=>'<p>Caption</p>',setRichEditorHtml(){},escapeHtml:s=>s,escapeAttr:s=>s,getErrorMessage:e=>e.message,showModal:(...a)=>modals.push(a),loadAppData(){refreshes++;},FileReader:class {readAsDataURL(file){if(file.unreadable)this.onerror();else {this.result=file.corrupt?'data:image/png;base64,corrupt':png;this.onload();}}},google:{script:{get run(){const chain={withSuccessHandler(fn){this.ok=fn;return this;},withFailureHandler(fn){this.fail=fn;return this;}};for(const name of ['uploadTribePhoto','previewRecapImageUrl'])chain[name]=(...args)=>{requests.push({name,args});pending.push(chain);};return chain;}}}});
 vm.runInContext("let PHOTO_FILES=[],PHOTO_UPLOAD_BUSY=false,PHOTO_MODE='upload',PHOTO_ADMIN_LIST_VERSION=0,PHOTO_MAX_BYTES=3145728,PHOTO_IMPORT_ERROR='This image could not be imported. Try another image URL or upload the photo directly.',APP_DATA={weekNumber:9},ADMIN_PASSCODE='key',ADMIN_ACCESS_ROLE='',SELECTED_RECAP_WEEK=null;"+source.slice(source.indexOf('function renderPhotoFiles()'),source.indexOf('\nfunction showModal(')),c);
 return {c,get,requests,pending,modals,refreshes:()=>refreshes};
}
const image=name=>({name,type:'image/png',size:100});const flush=()=>new Promise(r=>setImmediate(r));
test('multiple previews, one-week batch, duplicate-click guard and cleared success queue',async()=>{
 const f=fixture();await f.c.loadPhotoFiles([image('a'),image('b')]);assert.match(f.get('photoFileList').innerHTML,/<img/);const upload=f.c.uploadPhoto();await flush();await f.c.uploadPhoto();assert.equal(f.requests.length,1);assert.equal(f.get('adminRecapWeek').disabled,true);
 f.get('adminRecapWeek').value='8';f.pending.shift().ok({ok:true});await flush();assert.deepEqual(f.requests.map(r=>r.args[1].week),[4,4]);f.pending.shift().ok({ok:true});await upload;await f.c.uploadPhoto();assert.equal(f.requests.length,2);assert.equal(f.refreshes(),1);
});
test('bad and oversized images are rejected before save while other valid photos continue',async()=>{
 const f=fixture();await f.c.loadPhotoFiles([{...image('large'),size:4*1024*1024},{...image('broken'),corrupt:true},image('fail'),image('good'),{...image('heic'),type:'image/heic'}]);const upload=f.c.uploadPhoto();await flush();f.pending.shift().fail(new Error('Upload failed'));await flush();f.pending.shift().ok({ok:true});await upload;assert.equal(f.requests.length,2);assert.match(f.get('photoFileList').innerHTML,/3 MB/);assert.match(f.get('photoFileList').innerHTML,/Upload failed/);assert.doesNotMatch(f.get('photoFileList').innerHTML,/>good</);
 const request=f.requests[0].args[1];const retry=f.c.uploadPhoto();await flush();assert.equal(f.requests[2].args[1].requestId,request.requestId);f.pending.shift().ok({ok:true});await retry;
});
test('five-file limit is enforced without silently truncating selection',async()=>{const f=fixture();await f.c.loadPhotoFiles(Array.from({length:6},(_,i)=>image(''+i)));assert.equal(f.requests.length,0);assert.match(f.modals.at(-1)[1],/5 photos/);assert.equal(f.get('photoFileList').innerHTML,'');});
test('week changes clear pending photos; invalid week cannot fall back to current week',async()=>{const f=fixture();f.get('adminRecapWeek').value='';await f.c.loadPhotoFiles([image('a')]);assert.match(f.modals.at(-1)[1],/valid recap week/);f.get('adminRecapWeek').value='4';await f.c.loadPhotoFiles([image('a')]);f.get('adminRecapWeek').value='7';await f.c.uploadPhoto();assert.equal(f.requests.length,0);f.c.recapPhotoWeekChanged();assert.equal(f.get('photoFileList').innerHTML,'');});
test('URL preview downloads once, confirms decoding, then saves identical bytes without hotlinking',async()=>{
 const f=fixture();f.c.setRecapPhotoMode('import');f.get('photoImportUrl').value='https://example.com/a.png';const preview=f.c.previewRecapImage();await flush();assert.equal(f.requests[0].name,'previewRecapImageUrl');assert.equal(f.get('photoUploadButton').disabled,true);f.pending.shift().ok({week:4,dataUrl:png,mimeType:'image/png',fileName:'import.png',size:100});await preview;assert.equal(f.requests.length,1);assert.equal(f.get('photoUploadButton').disabled,false);
 const upload=f.c.uploadPhoto();await flush();assert.equal(f.requests[1].name,'uploadTribePhoto');assert.equal(f.requests[1].args[1].dataUrl,png);assert.equal(f.requests[1].args[1].week,4);assert.equal(f.requests[1].args[1].url,undefined);f.pending.shift().ok({ok:true});await upload;
});
test('failed or undecodable imports never become savable photos',async()=>{for(const response of [null,{week:4,dataUrl:'data:image/png;base64,corrupt',size:100}]){const f=fixture();const preview=f.c.previewRecapImage();await flush();const request=f.pending.shift();response?request.ok(response):request.fail(new Error('Access denied'));await preview;assert.equal(f.get('photoUploadButton').disabled,true);assert.match(f.get('photoUploadStatus').textContent,/This image could not be imported/);await f.c.uploadPhoto();assert.equal(f.requests.length,1);}});
test('editing URL invalidates its previous preview and changing modes discards stale selections',async()=>{const f=fixture();await f.c.loadPhotoFiles([image('a')]);f.c.setRecapPhotoMode('import');assert.equal(f.get('photoFileList').innerHTML,'');await f.c.loadPhotoFiles([image('a')]);f.c.clearRecapImagePreview();assert.equal(f.get('photoUploadButton').disabled,true);});
test('browser scripts parse and all new UI controls exist once',()=>{for(const m of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);for(const id of ['photoUploadChoice','photoImportChoice','photoImportPanel','photoImportUrl','photoImportPreviewButton','adminRecapPhotos'])assert.equal(source.split('id="'+id+'"').length-1,1,id);assert.match(source,/id="photoInput"[^>]*multiple/);});
